### Create a new resource
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"username": "laisdonida",
"password": "novasenha123"
}
### Register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
"firstname": "Jhin",
"lastname": "khoda",
"username": "quatro",
"password": "quatroquatro"
}


### Read all users
GET http://localhost:3000/api/users/6/posts
Content-Type: application/json


### Read all posts
GET http://localhost:3000/api/posts

### Update a user by ID
PATCH http://localhost:3000/users/6
Content-Type: application/json

{
    "password":"novasenha123"
}
    

### Update a post by ID
PATCH http://localhost:3000/posts/6
Content-Type: application/json

{
"text":"Hi"
}

### Delete a user by ID
DELETE http://localhost:3000/users/6

### Delete a post by ID
DELETE http://localhost:3000/posts/6